import archiver from 'archiver';
import { Writable } from 'stream';
import { BrandPalette } from './palette';
import { FontPairing } from './typography';
import { SocialAsset } from './socialKit';
import { FaviconAsset } from './favicons';

interface PackageAssets {
  domainName: string;
  logoPng: Buffer;
  logoPngTransparent?: Buffer;
  logoSvg: string;
  palette: BrandPalette;
  fonts: FontPairing;
  socialKit?: SocialAsset[];
  favicons: FaviconAsset[];
  brandPdf?: Buffer;
  tier: 'LOGO_ONLY' | 'BRAND_KIT' | 'BRAND_KIT_PRO';
}

export async function assembleZip(assets: PackageAssets): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const output = new Writable({
      write(chunk, _, callback) { chunks.push(chunk); callback(); }
    });
    output.on('finish', () => resolve(Buffer.concat(chunks)));

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.on('error', reject);
    archive.pipe(output);

    const name = assets.domainName;

    archive.append(assets.logoPng, { name: `${name}/logo/logo-2000px.png` });
    if (assets.logoPngTransparent) {
      archive.append(assets.logoPngTransparent, { name: `${name}/logo/logo-2000px-transparent.png` });
    }
    archive.append(Buffer.from(assets.logoSvg), { name: `${name}/logo/logo.svg` });

    for (const favicon of assets.favicons) {
      archive.append(favicon.buffer, { name: `${name}/favicons/${favicon.filename}` });
    }

    if (assets.tier !== 'LOGO_ONLY') {
      if (assets.socialKit) {
        for (const asset of assets.socialKit) {
          archive.append(asset.buffer, { name: `${name}/social-media/${asset.filename}` });
        }
      }

      archive.append(Buffer.from(assets.palette.cssVars), { name: `${name}/brand/colors.css` });
      archive.append(Buffer.from(JSON.stringify({
        primary: assets.palette.primary,
        secondary: assets.palette.secondary,
        accent: assets.palette.accent,
        light: assets.palette.light,
        dark: assets.palette.dark,
      }, null, 2)), { name: `${name}/brand/colors.json` });

      const fontGuide = `
# ${name} Typography Guide

## Heading Font
${assets.fonts.heading.name}
Weights: ${assets.fonts.heading.weights.join(', ')}
CSS: font-family: ${assets.fonts.heading.cssFamily};

## Body Font
${assets.fonts.body.name}
Weights: ${assets.fonts.body.weights.join(', ')}
CSS: font-family: ${assets.fonts.body.cssFamily};

## Monospace Font
${assets.fonts.mono.name}
CSS: font-family: ${assets.fonts.mono.cssFamily};

## Google Fonts Import
${assets.fonts.googleFontsUrl}
      `.trim();
      archive.append(Buffer.from(fontGuide), { name: `${name}/brand/typography.md` });

      if (assets.brandPdf) {
        archive.append(assets.brandPdf, { name: `${name}/brand/brand-guidelines.pdf` });
      }
    }

    const readme = `# ${name} Brand Identity Package
Generated by Sparkdomain

## Contents
${assets.tier === 'LOGO_ONLY' ? `- logo/ — PNG (original + transparent) + SVG\n- favicons/ — All sizes + .ico + webmanifest` :
`- logo/ — PNG (original + transparent background) + SVG
- favicons/ — All sizes + .ico + webmanifest
- social-media/ — 20 platform-sized assets
- brand/ — Color palette, typography guide, brand guidelines PDF`}

## License
These files are licensed for commercial use for the brand "${name}".
You may use these assets in any commercial or personal project.
    `.trim();
    archive.append(Buffer.from(readme), { name: `${name}/README.md` });

    archive.finalize();
  });
}
